trigger:
  branches:
    include:
      - main
  paths:
    include:
      - algod/
      - indexer/
      - azure-pipelines.yml

# no PR triggers
pr: none

jobs:
- job: DockerBuildAndPush
  strategy:
    matrix:
      algod:
        BUILD_DIR: 'algod'
        DOCKER_REPO: 'makerxau/algorand-sandbox-dev'
      indexer:
        BUILD_DIR: 'indexer'
        DOCKER_REPO: 'makerxau/algorand-indexer-dev'
    maxParallel: 2
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    displayName: DockerHub Login
    inputs:
      command: login
      containerRegistry: "MakerX Docker Hub"    
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker buildx create --use
      docker buildx build --platform linux/amd64,linux/arm64 -t $(DOCKER_REPO):latest --push $(BUILD_DIR)
    displayName: Build and Push
  - task: Docker@2
    displayName: DockerHub Logout
    inputs:
      command: logout
      containerRegistry: "MakerX Docker Hub"
