# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build algod
  inputs:
    command: buildAndPush
    buildContext: algod
    Dockerfile: algod/Dockerfile
    repository: makerxau/algorand-sandbox-dev
    containerRegistry: "MakerX Docker Hub"
    tags: |
      latest
- task: Docker@2
  displayName: Build indexer
  inputs:
    command: buildAndPush
    buildContext: indexer
    Dockerfile: indexer/Dockerfile
    repository: makerxau/algorand-indexer-dev
    containerRegistry: "MakerX Docker Hub"
    tags: |
      latest
